export function getSchedule() {
	const db = {
		JC2: {
			"Monday": {
				"Math": {
					Start: "07.20",
					End: "08.40",
					Room: "303",
					Teacher: "Mr. Danilo",
		    },
		    "Chapel": {
		      Start: "08.40",
					End: "10.00",
		      Room: "4th Fl.",
		      Teacher: "N/A",
		    },
		    "Recess": {
		      Start: "10.00",
					End: "10.15",
		      Room: "N/A",
		      Teacher: "N/A",
		    },
				"Chem": {
					Start: "10.15",
					End: "11.35",
					Room: "Lab",
					Teacher: "Mm. Madhu",
				},
				"BS": {
					Start: "10.15",
					End: "11.35",
					Room: "303",
					Teacher: "Mr. Boon",
				},
				"CL": {
					Start: "11.40",
					End: "13.00",
					Room: "208",
					Teacher: "LS Evelyn",
				},
				"Lunch": {
					Start: "13.00",
					End: "13.15",
					Room: "N/A",
					Teacher: "N/A",
				},
				"Phy": {
					Start: "13.15",
					End: "14.35",
					Room: "Lab",
					Teacher: "Mr. Nap",
				},
			},
			"Tuesday": {
				"Assembly": {
					Start: "07.00",
					End: "07.20",
					Room: "1st Fl.",
					Teacher: "N/A",
				},
				"Devotion": {
					Start: "07.20",
					End: "07.50",
					Room: "N/A",
					Teacher: "N/A",
				},
				"CE": {
					Start: "07.50",
					End: "09.10",
					Room: "201",
					Teacher: "Mr. Leo",
				},
				"Chem": {
					Start: "09.15",
					End: "10.35",
					Room: "Lab",
					Teacher: "Mm. Madhu",
				},
				"BS": {
					Start: "09.15",
					End: "10.35",
					Room: "311",
					Teacher: "Mr. Boon",
				},
				"Recess": {
					Start: "10.35",
					End: "10.55",
					Room: "N/A",
					Teacher: "N/A",
				},
				"GP": {
					Start: "10.55",
					End: "12.15",
					Room: "303",
					Teacher: "Mm. Martha",
				},
				"Math": {
					Start: "12.20",
					End: "13.40",
					Room: "301",
					Teacher: "Mr. Danilo",
				},
				"Lunch": {
					Start: "13.40",
					End: "14.05",
					Room: "N/A",
					Teacher: "N/A",
				},
				"Bio": {
					Start: "14.05",
					End: "15.25",
					Room: "Lab",
					Teacher: "Mr. Indra",
				},
			},
			"Wednesday": {
				"Assembly": {
					Start: "07.00",
					End: "07.20",
					Room: "1st Fl.",
					Teacher: "N/A",
				},
				"Devotion": {
					Start: "07.20",
					End: "07.50",
					Room: "N/A",
					Teacher: "N/A",
				},
				"Math": {
					Start: "07.50",
					End: "09.10",
					Room: "201",
					Teacher: "Mr. Danilo",
				},
				"BI": {
					Start: "09.15",
					End: "10.35",
					Room: "303",
					Teacher: "Ibu Erna",
				},
				"Recess": {
					Start: "10.35",
					End: "11.00",
					Room: "N/A",
					Teacher: "N/A",
				},
				"Bio": {
					Start: "11.00",
					End: "12.20",
					Room: "Lab",
					Teacher: "Mr. Indra",
				},
			},
			"Thursday": {
				"Assembly": {
					Start: "07.00",
					End: "07.20",
					Room: "1st Fl.",
					Teacher: "N/A",
				},
				"Devotion": {
					Start: "07.20",
					End: "07.50",
					Room: "N/A",
					Teacher: "N/A",
				},
				"Math": {
					Start: "07.50",
					End: "09.10",
					Room: "301",
					Teacher: "Mr. Danilo",
				},
				"Phy": {
					Start: "09.15",
					End: "10.35",
					Room: "Lab",
					Teacher: "Mr. Nap",
				},
				"Recess": {
					Start: "10.35",
					End: "10.55",
					Room: "N/A",
					Teacher: "N/A",
				},
				"CL": {
					Start: "10.55",
					End: "12.15",
					Room: "303",
					Teacher: "LS. Evelyn",
				},
				"Math": {
					Start: "12.20",
					End: "13.40",
					Room: "301",
					Teacher: "Mr. Danilo",
				},
				"Lunch": {
					Start: "13.40",
					End: "14.05",
					Room: "N/A",
					Teacher: "N/A",
				},
				"GP": {
					Start: "14.05",
					End: "15.25",
					Room: "207",
					Teacher: "Mm. Martha",
				},
			},
			"Friday": {
				"Assembly": {
					Start: "07.00",
					End: "07.20",
					Room: "1st Fl.",
					Teacher: "N/A",
				},
				"Devotion": {
					Start: "07.20",
					End: "07.50",
					Room: "N/A",
					Teacher: "N/A",
				},
				"GP": {
					Start: "07.50",
					End: "09.10",
					Room: "302",
					Teacher: "Mm. Martha",
				},
				"Phy": {
					Start: "09.15",
					End: "10.35",
					Room: "Lab",
					Teacher: "Mr. Nap",
				},
				"Recess": {
					Start: "10.35",
					End: "10.55",
					Room: "N/A",
					Teacher: "N/A",
				},
				"Chem": {
					Start: "10.55",
					End: "12.15",
					Room: "Lab",
					Teacher: "Mm. Madhu",
				},
				"BS": {
					Start: "10.55",
					End: "12.15",
					Room: "207",
					Teacher: "Mr. Boon",
				},
				"Bio": {
					Start: "12.20",
					End: "13.40",
					Room: "Lab",
					Teacher: "Mr. Indra",
				},
				"Lunch": {
					Start: "13.40",
					End: "14.05",
					Room: "N/A",
					Teacher: "N/A",
				},
				"Math": {
					Start: "14.05",
					End: "15.25",
					Room: "301",
					Teacher: "Mr. Danilo",
				},
			},
		},
	}
	return db
}
